### ISSUE TITLE
Show meeting information popup just once on the begining of the session (and make it mandatory)

### ISSUE THREAD

**Issue by gadife** [ericman93/Scheddy#31]
Now it's popups when moving between weeks

**Comment by ericman93** [comment]
Its only pop once.
How do you want it to be mandatory?

**Comment by gadife** [comment]
it appears every time I browsing to next week.

About mandatory, do not allow ignore by click on some other area in the screen.

**Comment by ericman93** [comment]
The popup frequency has fixed.
